### ISSUE TITLE
Virus Total Scan

### ISSUE THREAD

**Issue by ArungPalakka** [cimo95/WinFn#1]
https://www.virustotal.com/gui/file/7cc3cb2a8ce350cd9137b2776fd2f76fb0f1681a67de2b4bbf6a9e4131e2b3a8
![image](https://user-images.githubusercontent.com/40798943/133597121-58b6578a-fa53-470b-8d64-37aec1bebe14.png)

**Comment by cimo95** [comment]
> https://www.virustotal.com/gui/file/7cc3cb2a8ce350cd9137b2776fd2f76fb0f1681a67de2b4bbf6a9e4131e2b3a8 ![image](https://user-images.githubusercontent.com/40798943/133597121-58b6578a-fa53-470b-8d64-37aec1bebe14.png)

The source code is already provided, if you have any doubts, you can compile the source code yourself.
I guarantee 100% this application is virus free, because I also use it everyday on my computer device.
